# Generated by Django 5.1.1 on 2024-09-23 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packs', '0001_initial'),
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpackinfo',
            name='shop',
            field=models.ManyToManyField(null=True, to='shop.shop'),
        ),
    ]
