# Generated by Django 5.1.1 on 2024-09-25 14:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packs', '0002_userpackinfo_shop'),
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpackinfo',
            name='shop',
        ),
        migrations.RemoveField(
            model_name='userpacks',
            name='pack_title',
        ),
        migrations.AddField(
            model_name='userpacks',
            name='shop',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='shop.shop'),
        ),
    ]
