# Generated by Django 5.1.1 on 2024-10-02 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packs', '0003_remove_userpackinfo_shop_remove_userpacks_pack_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpacks',
            name='containers',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
