# Generated by Django 5.1.1 on 2024-10-02 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='x_gis',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='shop',
            name='y_gis',
            field=models.FloatField(null=True),
        ),
    ]
